# Site settings
title: Cong Yu's Blog
SEOTitle: ML study Blog
header-img: img/post-bg-desk.jpg
email: 990800269@qq.com
description: "Share my reading notes with everyone."
keyword: "WZH, Cong Yu Blog, image recognition, deep learning, mechine learning"
url: "http://YC-wind.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/YC-wind/YC-wind.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Enjoy reading"
sidebar-avatar: /img/about_me.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:
#zhihu_username:
github_username:    YC-wind
#facebook_username:
#jianshu_username:
#twitter_username:


# for markdown
markdown: kramdown
mathjax: true
kramdown:
  input: GFM
  use_coderay: true
  hard_wrap: false

# highlight codes
# highlight: true


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Je
# Gems
# gems: [jekyll-paginate]


# Analytics settings
# Baidu Analytics
ba_track_id: 883e2f41b03c4d1d375cea18d8966dcb

# Google Analytics
ga_track_id: 'UA-111549663-1'            # Format: UA-xxxxxx-xx
ga_domain: auto


# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: fe40626b0b34324bac86   #生成的clientID
  clientSecret: 3f92dffbf42e8d86f84506d3788b4211cb03903f  #同上
  repo: YC-wind.github.io    #仓库名称
  owner: YC-wind    #github用户名
  admin: YC-wind
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "xueshu.io",
        href: "http://http://linkick.com/"
    },{
        title: "简书",
        href: "http://www.jianshu.com/u/"
    }
]


port: 4001
